<a href="https://colab.research.google.com/github/Samrath49/AI_ML_DL/blob/main/1.%20Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Preprocessing**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X,y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking Care of Missing values

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Taking care of Categorical variables

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting Dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,  test_size= 0.2, random_state = 1)

In [ ]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[1.0 0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


## Feature Scaling 

Applied coz some features might dominate other features and hence the dominated once will not perform better. Hence using it we balance the features importance.

Two techiques to do it is:

Standardization- Makes feature in range of -3 to +3.  Used all the time.

Normalization- Turns features in 0 or 1. Used for normal distributions only.


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# We never apply feature scalling on dummy variables. For eg on Country name.
X_train[:, 3: ] = sc.fit_transform(X_train[:, 3:]) #sc_fit computes sd and mean of column and transform use that values to generate standardization
X_test[:, 3:] = sc.transform(X_test[:, 3:]) # We don't use fit since we don't ever want to have new values for our test set as it should use mean and sd of train set.

In [ ]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358058 -0.28942984211696865 -1.0430254692900243]
 [1.0 0.0 1.0 -0.7745966692414834 0.0 -0.2767210428728636]
 [0.0 1.0 0.0 -0.7745966692414834 0.5788596842339373 0.659873256081444]
 [1.0 0.0 0.0 1.2909944487358058 -0.28942984211696865 -0.2767210428728636]
 [1.0 0.0 0.0 1.2909944487358058 -1.8812939737602963 -1.383605214364318]
 [0.0 1.0 0.0 -0.7745966692414834 1.1577193684678746 1.2558878099614579]
 [1.0 0.0 1.0 -0.7745966692414834 1.4471492105848434 1.5964675550357514]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7235746052924217 -0.5321558516785838]]


#### Why not to use fit on X_test
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:]) this gives us wrong test feature scalling as:
~~~
print(X_test)
[[1.0 0.0 1.0 0.0 -1.0 -1.0]
 [0.0 1.0 0.0 0.0 1.0 1.0]]
~~~

In [ ]:
print(X_test) # correct feature scalling

[[1.0 0.0 1.0 -2.775557561562892e-17 -1.0 -1.0]
 [0.0 1.0 0.0 -2.775557561562892e-17 1.0 1.0]]
