<a href="https://colab.research.google.com/github/Samrath49/AI_ML_DL/blob/main/23.%20ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [61]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [62]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the Dataset

In [63]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:,-1].values

In [64]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [65]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding the categorical data

### Label encoding the 'Gender'  column

In [66]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [67]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One hot encoding the 'Geography' column

In [68]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [69]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training and Test set

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

Feature scaling is absolutely important for deap learning

In [71]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [72]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [73]:
ann.add(tf.keras.layers.Dense(units = 7, activation= 'relu'))

### Adding the second hidden layer

In [74]:
ann.add(tf.keras.layers.Dense(units = 7, activation= 'relu'))

### Adding the output layer

In [75]:
ann.add(tf.keras.layers.Dense(units = 1, activation= 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [76]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [77]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5672 - accuracy: 0.7630
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4582 - accuracy: 0.7968
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4459 - accuracy: 0.8036
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4346 - accuracy: 0.8163
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8188
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4145 - accuracy: 0.8254
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4099 - accuracy: 0.8336
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4003 - accuracy: 0.8361
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4010 - accuracy: 0.8306
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4039 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [78]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting a single value

### Predicting the test set results

In [79]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making Confusion Matrix

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1519   76]
 [ 203  202]]


0.8605