<a href="https://colab.research.google.com/github/Samrath49/AI_ML_DL/blob/main/Special.%20ArtificialNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing Dataset

In [6]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into Training and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 000)

## Part 2 - Building the ANN

### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units = 1))
# If classification with 2 prediction values use sigmoid
# If classification with more than 2 prediction values then we use softmax
# If we are predicting single continuous value i.e. regression then we chose none

### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

## Part 3 - Training the ANN

### Training the ANN model on the Training set

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 855us/step - loss: 80112.6757
Epoch 2/100
240/240 [==============================] - 0s 907us/step - loss: 480.9801
Epoch 3/100
240/240 [==============================] - 0s 900us/step - loss: 473.9139
Epoch 4/100
240/240 [==============================] - 0s 950us/step - loss: 431.5618
Epoch 5/100
240/240 [==============================] - 0s 916us/step - loss: 401.0530
Epoch 6/100
240/240 [==============================] - 0s 901us/step - loss: 367.7622
Epoch 7/100
240/240 [==============================] - 0s 905us/step - loss: 327.9475
Epoch 8/100
240/240 [==============================] - 0s 909us/step - loss: 292.2567
Epoch 9/100
240/240 [==============================] - 0s 969us/step - loss: 249.1952
Epoch 10/100
240/240 [==============================] - 0s 814us/step - loss: 218.5664
Epoch 11/100
240/240 [==============================] - 0s 969us/step - loss: 180.8399
Epoch 12/100
240/240 [============================

### Predicting the results of the Test set

In [27]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[430.05 431.23]
 [461.11 460.01]
 [464.61 461.14]
 ...
 [471.87 473.26]
 [438.6  438.  ]
 [457.86 463.28]]
